sonar.projectKey=KiotoTeteria
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.coverage.exclusions=src/main.ts, src/**/*.module.ts, src/**/*.dto.ts, src/**/*.strategy.ts, src/**/*.decorator.ts, src/**/*.guard.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info